### PR TITLE
Update css-quiz.md

### PR DESCRIPTION
**Pull request by alinooshabadi**
Adding 3 new questions

### CODE REVIEW

**Review by monkrus — CHANGES_REQUESTED** [review]
This commit failed with errors, do you mind looking at it again.

**Review by monkrus — CHANGES_REQUESTED** [review]
This commit failed as well , do you mind looking at it again.

**Comment by Ebazhanov** [comment]
> This commit failed as well , do you mind looking at it again.
> it is
> @alinooshabadi reformat document and fix lint errors [0ae0f4c](https://github.com/Ebazhanov/in-quiz-questions/commit/0ae0f4cfcc877799abf3cfc415183b4bbc61b788)
> @alinooshabadi Add 3 new questions [f5daed0](https://github.com/Ebazhanov/in-quiz-questions/commit/f5daed0569f512d10bfd79fa588783d73b3904c9)

all good @monkrus Sergey, thanks for noticing:+1: :beer:! The build failed because of an unknown issue with `pull_request`! FYI I am working on it to fix it! So from my side green light for this PR! :green_apple:

**Review by Ebazhanov — COMMENTED** [review]
@alinooshabadi Thank you for the great input (new questions and reformatting) :punch:

**Pull request merged**
