### PR TITLE
Format C++ Code

### PR DESCRIPTION
**Pull request by tik9**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@tik9 my friend, unfortunately, there are some conflicts between your branch and master, could you please fix it! And we will merge it very quickly. Thank you in advance!

**Comment by tik9** [comment]
Should be ok now, you were too fast for me to see the conflicts;)

**Comment by tik9** [comment]
I accidentally closed it, now reopen.

**Review by Ebazhanov — APPROVED** [review]
Ok, now finally we can merge this fat PR, thank you @tik9! :nail_care:

**Pull request merged**
