### PR TITLE
All contributors/add ebazhanov

### PR DESCRIPTION
**Pull request by chilcot**
#### Q1. A dataset that includes _ can be used to create a map visualization. (Select all that apply.) 

A. house numbers, street names 
B. geospatial data 
C. city names, country names 
D. longitude, latitude 

- [  ] A, B, C, D 
- [  ] A, C, D 
- [  ] B, C, D 
- [  ] D

#### Q2. How do you create a chart visual in Power Bl Desktop Report view? (Select all that apply.) 

A. Click New Visual on the Home tab. 
B. Select a chart visual in the Visualizations pane. 
C. Click New Visual on the Data Tools tab. 
D. Select a field that contains values. 

- [  ] A, B, or D 
- [  ] B or D 
- [  ] B orC 
- [  ] A or B

#### Q3. What daily sales number does this DAX measure formula calculate? CALCULATE(SUM([Sales]) ,DATESHTD([Date] )) 

- [  ] running total sales in each month that starts over each month 
- [  ] total sales for the entire month 
- [  ] running total in entire year for the entire month 
- [  ] rolling average over 12 months of sales

#### Q4. You are creating a report in Power Bl Desktop and want to restrict the data to records where Country="Canada". To accomplish this, what do you need to create? 

- [  ] a directive 
- [  ] a custom column 
- [  ] an indexed column 
- [  ] a parameter

#### Q5. What is the primary benefit of using visualizations such as line charts, bar charts, and column charts? 

- [  ] They are easier to create than other visualizations. 
- [  ] They require fewer resources than more complex visualizations. 
- [  ] They are also used in Excel, so they feel familiar to users. 
- [  ] They are free to use.

#### Q6. In Power Bl service, deleted pages are available after deletion until 

- [  ] midnight of the day on which they are deleted 
- [  ] the next billing cycle 
- [  ] you empty the Recycle Bin 
- [  ] the report has been saved

#### Q7. You need to add a required color to a bar chart. How can you add an exact color value to an existing bar chart? 

- [  ] Click the color in the visual (e.g., the bars) and right-click to select the color. 
- [  ] You cannot select custom colors in a bar chart or related visual. 
- [  ] Select the value closest to this color from the color formatting options. 
- [  ] Enter the hex value into the color formatting options.

#### Q8. The Excel function IF is nearly the same as which DAX function? 

- [  ] SWITCH 
- [  ] IF 
- [  ] IFX 
- [  ] IFS

#### Q9. Consider the Power Bl extract, transform, and load process (ETL). During this process, data is read and then

- [  ] stored in SQL Server 
- [  ] written to an OLAP cube 
- [  ] assigned a data type 
- [  ] sorted by primary key

#### Q1- [  ]. Power Bl's Publish to Web option allows you to embed visualizations within _. (Select all that apply.) 

A. blog posts 
B. email messages 
C. web sites 
D. text messages 

- [  ] A,C 
- [  ]  C
- [  ] A, B, C 
- [  ] A, B, C, D 

#### Q11. What can you do within the Power Bl Desktop Query Settings pane? (Select all that apply.) 

A. Rename a query step. 
B. Delete a query step. 
C. Delete from one query step to the end. 
D. Reorder the steps. 

- [  ] B, C, D 
- [  ] A, B, C, D 
- [  ] A, B, D 
- [  ] A, B, C

#### Q12. After you enter text in the Q&A box or O&A visual, Power Bl will _ your data to create a list of appropriate visualizations. 

- [  ] filter and group 
- [  ] sort and filter 
- [  ] sort, filter, and group 
- [  ] sort and group

#### Q13. You just deleted a dashboard in the Power Bl service and want to get it back. What should you do? 

- [  ] Press Ctrl+Z. 
- [  ] Select Undo from the toolbar. 
- [  ] You cannot undo the deletion of a dashboard. 
- [  ] Recover it from the Recycle Bin.

#### Q14. You have a sales data source and want to relate the tables. The table that contains sales transactions is a table that contains product information is a _ table . 

- [  ] dimension; fact 
- [  ] lookup; data 
- [  ] data; lookup 
- [  ] data; supporting

#### Q15. When you are creating a formula in the Power Query Editor, what does IntelliSense provide a list of? (Select all that apply.) 

A. columns 
B. tables 
C. functions 
D. data sources 

- [  ] B,C 
- [  ] A, C, D 
- [  ] C,D 
- [  ] A, B, C

#### Q16. You want to delete a dataset but the Power Bl service will not let you. What is the most likely cause? 

- [  ] A tile on your dashboard contains data from that dataset. 
- [  ] The dataset is already being used in a published app. 
- [  ] A report contains data from that dataset. 
- [  ] The dataset is in your workspace.

#### Q17. One of your data columns includes the city, state, and postal code line of a mailing address. You need to separate the fields so you can access the geospatial elements for a map visualization. What transformation should you apply? 

- [  ] Replace values 
- [  ] Split column 
- [  ] Modify data type 
- [  ] Best fit geospatial

#### Q18. Formatting options within a visualization depend on what? 

- [  ] the visualization you are formatting 
- [  ] the editor you use 
- [  ] the visualization group 
- [  ] your permissions

#### Q19. What tool can you use in Power Bl Desktop to reduce data? 

- [  ] report editor 
- [  ] Power Query Editor 
- [  ] dashboard 
- [  ] data modeler

#### Q20. What is NOT a valid data connection type for Power Bl Desktop? 

- [  ] Azure data 
- [  ] file data 
- [  ] relationships data 
- [  ] database data

#### Q21. Which data type can be uploaded directly to powerbi.com? 

- [  ] Excel files 
- [  ] comma-separated value (CSV) files 
- [  ] Power Bl Desktop files 
- [  ] all of these answers

#### Q22. What does Power Bl Premium provide? 

- [  ] Power Bl Report Server 
- [  ] report sharing without a per-user licens
- [  ] all of these answers 
- [  ] dedicated capacity for your company

#### Q23. You have a report in Power Bl service and want to save the state of a report page for easy access. What feature helps you do this? 

- [  ] views 
- [  ] filters 
- [  ] bookmarks 
- [  ] slicers

#### Q23. What daily sales number does this DAX measure formula calculate? 

CALCULATE(SUM([Sales]) ,DATESHTD([Date] )) 

- [  ] running total sales in each month that starts over each month 
- [  ] total sales for the entire month 
- [  ] running total in entire year for the entire month 
- [  ] rolling average over 12 months of sales

### CODE REVIEW

**Comment by chilcot** [comment]
I am sorry, i was unable to create a Power BI folder. would you be able to do this the question are above.

**Review by chilcot — COMMENTED** [review]
Done

**Comment by Ebazhanov** [comment]
no worries I added it thank you for the input @chilcot :muscle:
here it is https://github.com/Ebazhanov/in-quiz-questions/blob/master/microsoft-power-bi/microsoft-power-bi-quiz.md
if you want to update anything feel free to creat PR

**Comment by Ebazhanov** [comment]
@all-contributors add @chilcot  for code, design

**Pull request closed without merging**
