### PR TITLE
Edit answers of git

### PR DESCRIPTION
**Pull request by SarahTeoh**
I edited answers of Q5, 24, 28, 42, 43. Please refer to the explanation in brackets above the questions.

#### Q5. Which of the following is true you when you use the following command?

`git add -A`

- [x] All new and updated files are staged
- [ ] Files are staged in alphabetical order.
- [ ] All new files are staged
- [ ] Only updated files are staged

#### Q24. You find that your project has a tag and branch both named push-notifications, which causes confusion when trying to print out given reference. How can you specify which branch you want to look at?

- [ ] use git show ref/push-notifications
- [ ] use git show push-notifications
- [ ] use git show head/refs/push-notifications <<--chose this one not sure though!
- [x] use git show refs/head/push-notifications

#### Q43. You find that your project has a tag and branch both named push-notification, which causes confusion when trying to print out a given reference. How can you specify which branch you want to look at?

- [ ] Use git show head/refs/push-notifications.
- [ ] Use git show push-notifications.
- [ ] Use git show refs/push-notifications.
- [x] Use git show refs/head/push-notifications.

#### Q28. Which of the following is true of the git push command?

- [x] By default a push doesn't send tags to the remote repository.
- [ ] Commits can only be tagged when they are created.
- [ ] Tags are pushed to the remote repository with their respective commits.
- [ ] Only annotated tags are automatically pushed to the remote repository with a commit.

#### Q42. Your current respository has three branches: master,beta and ousg-notifications. You've just finished the notification feature and commit the changes to the push-notification branch, and you want to include them in the beta branch. How can you acccomplish this?

- [ ] Check out the master branch and run git merge beta -> push-notifications..
- [ ] Delete the push-notification branch;it will be committed to the mastre branch automatically.
- [ ] Check out the push-notifications branch and run git merge beta.
- [x] Check out the beta branch and run git merge push-notifications.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@SarahTeoh thank you for the answers and reference links
would be great if you will add all of them inside "git-quiz.md" 
to let other people find it as well 
Thank you! After we can merge your PR!!!!
Have a good day!

**Review by Ebazhanov — APPROVED** [review]
Thank you @SarahTeoh, very good!  :muscle:
will merge it now

**Comment by SarahTeoh** [comment]
> @SarahTeoh thank you for the answers and reference links
> would be great if you will add all of them inside "git-quiz.md"
> to let other people find it as well
> Thank you! After we can merge your PR!!!!
> Have a good day!

Thank you for the feedback. As per request, I have added the reference links to "git-quiz.md".

**Comment by Ebazhanov** [comment]
@all-contributors please add @SarahTeoh for code, design

**Pull request merged**
