### PR TITLE
Editing Q36 in html

### PR DESCRIPTION
**Pull request by sai-github**
wraps options in code and marks answer

### CODE REVIEW

**Comment by sai-github** [comment]
may I know the reason why the check failed, I couldn't understand the error msg `[error]Resource not accessible by integration`

**Comment by Ebazhanov** [comment]
> may I know the reason why the check failed, I couldn't understand the error msg `[error]Resource not accessible by integration`

yes good question I am waiting with this issue since the beginning of this repo ))) if you could help I will be very happy! 
thank you!

**Review by Ebazhanov — APPROVED** [review]
So thank you @sai-github Approved!!! :fist:

**Comment by Ebazhanov** [comment]
@all-contributors add @sai-github  for design

**Comment by sai-github** [comment]
> > may I know the reason why the check failed, I couldn't understand the error msg `[error]Resource not accessible by integration`
> 
> yes good question I am waiting with this issue since the beginning of this repo ))) if you could help I will be very happy!
> thank you!

Do you think this will resolve the issue https://github.com/actions/first-interaction/issues/10#issuecomment-670968624
Changing `pull_request` to `pull_request_target` in workflow file

**Comment by Ebazhanov** [comment]
thanks a lot, @sai-github I pushed the changes let's !!!!!

**Pull request merged**
