### PR TITLE
Provided answer and explanation for Q62

### PR DESCRIPTION
**Pull request by asarma2012**
Provided answer and explanation for Q62 about activations and softmax.

Follow-up to #683

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@asarma2012 Thank you for the great input but suddenly there are some conflicts in your PR, could you please fix them, then we can merge your changes. Thank you in advance!

**Comment by asarma2012** [comment]
Hi @Ebazhanov, please elaborate on the conflicts of the PR.

Sincerely,

asarma2012

**Comment by Ebazhanov** [comment]
> Hi @Ebazhanov, please elaborate on the conflicts of the PR.
> 
> Sincerely,
> 
> asarma2012

yes, ok you have conflicts between your branch and master branch of this repo
image

to fix conflicts you need to pull the latest changes from master branch and then merge those changes into your local branch and then push it 
I just start google the same question and found this [articles](https://remarkablemark.org/blog/2017/06/02/git-update-branch/) maybe you can find something more details, if not please drop me a [message](ebazhanov@yahoo.com) we can talk privately or plan B I can fix it by myself.

**Comment by asarma2012** [comment]
@Ebazhanov , I think I resolved the conflicts. Please check.

**Review by Ebazhanov — APPROVED** [review]
Wohoooohoooooo!!! Nice @asarma2012, thank you :+1: going to merge it immediately! :muscle:

**Comment by Ebazhanov** [comment]
> @Ebazhanov , I think I resolved the conflicts. Please check.

yea you did it !!!!

**Comment by Ebazhanov** [comment]
@all-contributors please add @asarma2012 for code, design

**Pull request merged**
