### PR TITLE
added Q87. What information does the git config file store?

### PR DESCRIPTION
**Pull request by frexcuadillera**
source answer: https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-config#:~:text=The%20git%20config%20command%20is,modify%20a%20configuration%20text%20file.

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@frexcuadillera thanks a lot for this PR but I want to ask for small improvements, please move the link which you posted in your comment -> post it inside the code to make it shared with everyone in the future! Thanks!

**Comment by frexcuadillera** [comment]
I just added the link below, I don't know the proper format, I only copied the format from Q23

**Review by Ebazhanov — APPROVED** [review]
Looks super cool now! I am sure with your link it will be very useful for everyone! Approved :+1:

**Comment by Ebazhanov** [comment]
@all-contributors please add @frexcuadillera for code, design

**Pull request merged**
