### PR TITLE
Adding answers to Q37, Q39, Q42,

### PR DESCRIPTION
**Pull request by shaye059**
Tried to include some justification and sources for each answer.

Q37: Logistic regression is far better than linear regression at binary classification since it biases the result toward one extreme or the other. K-means clustering can be used for classification but is not as accurate in most scenarios. Source: https://www.kaggle.com/minc33/k-means-clustering-vs-logistic-regression

Q38: This one is pretty straight forward and a fundamental concept. Source: https://towardsdatascience.com/machine-learning-for-beginners-d247a9420dab

Q42: This one is similar to an example talked about in the Stanford Machine Learning course. Source: https://www.coursera.org/learn/machine-learning/home/welcome

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@shaye059 thanks for PR also would be great if you will add your explanation inside the *.md file, it would be useful later for everyone. Just copy/past it from your PR message to the code. Can you do it? Then we can merge your PR, is it ok?

**Comment by monkrus** [comment]
I` ll gladly merge once the abovementioned conditions are met.

**Comment by monkrus** [comment]
@shaye059 Great contribution! Many thanks for your work! 🔥

**Comment by monkrus** [comment]
@all-contributors please add @shaye059 for code

**Pull request merged**
