### PR TITLE
beautifying Q67

### PR DESCRIPTION
**Pull request by Daniboy370**

### CODE REVIEW

**Comment by Daniboy370** [comment]
@Ebazhanov please approve PR

**Review by Ebazhanov — APPROVED** [review]
thanks but please do `git pull` looks like your local master branch is not up today
so I fixed some conflicts. The rest is good, thank you @Daniboy370 :punch:

**Comment by Ebazhanov** [comment]
@all-contributors please add @Daniboy370 for fundingFinding

**Comment by Daniboy370** [comment]
Thanks a lot @Ebazhanov !
I learned a lot from my interaction here !
All the best :)

**Comment by Ebazhanov** [comment]
thank you, LinkedIn for providing such opportunity :blush:

**Pull request merged**
