### PR TITLE
Hotfix: MySQL markdown issues and formatting

### PR DESCRIPTION
**Pull request by marcobiedermann**
Fix markdown issues and improve styles of document

- Fix checkbox markdown declaration: Unchecked checkboxes must contain space between braces
- Add missing language to code blocks: Is is recommended to set the language per code clock (e.g. `sql`, `xml`)
- Format markdown using [Prettier](https://prettier.io/)
- Optimize images using ImageOptim: This reduces the overall file-size by 15% without losing any quality

image

Preview: https://github.com/marcobiedermann/in-quiz-questions/blob/hotfix/mysql/mysql/mysql-quiz.md

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@marcobiedermann Thank you very much for your pull request, the first thing I liked was the way you designed the message in it, it is very informative. :muscle:

Also, special thanks for optimizing the files, yes it looks much better, you're right :punch:

I would also like to ask you if you could add your **prettier** to this repository? would be very useful for all subsequent PR 

And please fix Conflicting files :point_left:

**Comment by marcobiedermann** [comment]
@Ebazhanov 

You are very welcome. Thanks for your feedback.
I've rebased my pull request to the latest `master`.

As requested, I've added Prettier to the repository and formatted all files in a separate pull request (#737)

**Review by Ebazhanov — APPROVED** [review]
Thank you for rebasing @marcobiedermann, I am happy to approve and merge your PR!

**Comment by Ebazhanov** [comment]
@all-contributors please add @marcobiedermann for code, design

**Pull request merged**
