### PR TITLE
Remove duplicated questions

### PR DESCRIPTION
**Pull request by Daniboy370**
no. 85 and no. 86 appeared identical

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@Daniboy370 thanks for PR but could you please check conflicts? Thank you in advance!

**Review by Daniboy370 — COMMENTED** [review]
Looks good to me

**Review by Ebazhanov — APPROVED** [review]
Thanks, @Daniboy370 all good merged!

**Comment by Daniboy370** [comment]
Thank you @Ebazhanov ,
I'm still learning how to cooperate on Git, still
I'm sorry if I do some mistakes. We all were beginners once ... 😁

**Pull request merged**
