### PR TITLE
latest c++,git and CSS question added which is asked to me on my linkedIn assessment

### PR DESCRIPTION
**Pull request by BalkrishnaBhatt**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
Hello, @BalkrishnaBhatt! Sorry for the delay with the review I was on vacation. Could you please fix conflicts between your branch and master? Thank you in advance!

**Comment by BalkrishnaBhatt** [comment]
@Ebazhanov  Thanks for replying.
I have resolved conflicts you can check and merge my PR!.
Thank you so much for such wonderful repo! Big kudos to you!

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
OMG, I am so sorry, I merged some other PR and it triggers one more conflicts, could you please fix it again @BalkrishnaBhatt, thank you in advance!

**Comment by Ebazhanov** [comment]
> OMG, I am so sorry, I merged some other PR and it triggers one more conflicts, could you please fix it again @BalkrishnaBhatt, thank you in advance!

I am promised to merge your PR as soon as you make updates :punch:

**Comment by Ebazhanov** [comment]
> > OMG, I am so sorry, I merged some other PR and it triggers one more conflicts, could you please fix it again @BalkrishnaBhatt, thank you in advance!
> 
> I am promised to merge your PR as soon as you make updates 👊

can still see the conflicts 
image

**Comment by BalkrishnaBhatt** [comment]
not an issue @Ebazhanov! Finally, I resolved all the conflicts !! 😎🤩
Thanks for all the support!

**Review by Ebazhanov — APPROVED** [review]
Thank you for your contribution! No, actually no support from me you did everything by yourself! :muscle:

**Comment by Ebazhanov** [comment]
@all-contributors please add @BalkrishnaBhatt for design, code

**Comment by BalkrishnaBhatt** [comment]
> @Ebazhanov
> 
> I've put up [a pull request](https://github.com/Ebazhanov/in-quiz-questions/pull/945) to add @BalkrishnaBhatt! 🎉



> @Ebazhanov
> 
> I've put up [a pull request](https://github.com/Ebazhanov/in-quiz-questions/pull/945) to add @BalkrishnaBhatt! 🎉

Thanks, mate

**Pull request merged**
