### PR TITLE
Updating typos and fixing wrong answers.

### PR DESCRIPTION
**Pull request by kamaljyotwal**
Some typos have been corrected along with answer changes to question 22 and 34 and some HTML entities encoded.

### CODE REVIEW

**Comment by kamaljyotwal** [comment]
Hi repo owner, I was browsing this repo. and came across some answers which needed correction so I have made some changes, I am also attaching screenshots of the write answers.

This is my first PR so am unaware of the failing check thing.
Thanks

MqcorrectSS
q34ss

**Review by Ebazhanov — APPROVED** [review]
Hello, @kamaljyotwal! Thank you for the detailed PR, yes the job failed but is always failed for the first one, has no idea how to fix it. So thank you for your contribution!!!! Great job! :star2:

**Comment by Ebazhanov** [comment]
@all-contributors please add @kamaljyotwal  for design

**Comment by kamaljyotwal** [comment]
Thanks, @Ebazhanov for your generous reply and adding me in, will be happy to edit/add more stuff if I come across anything doubtful.
Thanks for reading.

**Pull request merged**
