### PR TITLE
Pluralsight skill tests

### PR DESCRIPTION
**Pull request by tik9**
Does it look good? Tests from another company.

### CODE REVIEW

**Review by Ebazhanov — COMMENTED** [review]
@tik9 thanks, I messaged you to your email!

**Comment by tik9** [comment]
Hi Evgeni,
either we can have it in your repo or in mine. At present it is in your
repo in the folder pluralsight.
If I have it in my repo, I cannot send you a pull request right? Bu you can
then fork it.
Should we do it this way and I delete the folder in your repo?
Is Pluralsight skill tests interesting to add to Linkedin tests ?

Wie geht es mit Deutsch?
Gruß nach Berlin

Am Mi., 28. Okt. 2020 um 21:34 Uhr schrieb Evgenii <notifications@github.com

**Comment by Ebazhanov** [comment]
I think I will do as you suggestedadd information about your repository to my Readme for everyone to seeand to start I will also make a contribution thereand I will ask someone else to do it too
But you have to prepare your repository a bitplease add there https://allcontributors.org/docs/en/overview
-- 
Best Regards / Beste GrüßeEvgenii 

    On Thursday, October 29, 2020, 07:39:58 AM GMT+1, Timo Körner <notifications@github.com> wrote:  
 
 

Hi Evgeni,
either we can have it in your repo or in mine. At present it is in your
repo in the folder pluralsight.
If I have it in my repo, I cannot send you a pull request right? Bu you can
then fork it.
Should we do it this way and I delete the folder in your repo?
Is Pluralsight skill tests interesting to add to Linkedin tests ?

Wie geht es mit Deutsch?
Gruß nach Berlin

Am Mi., 28. Okt. 2020 um 21:34 Uhr schrieb Evgenii <notifications@github.com

**Comment by tik9** [comment]
Thanks for the email, so I will delete the files in your repo, send a pr and answer you in the mail.

**Comment by Ebazhanov** [comment]
> Thanks for the email, so I will delete the files in your repo, send a pr and answer you in the mail.

ok, thanks! but maybe the simplest way is to close this PR without deleting

**Comment by Ebazhanov** [comment]
for the following questions https://github.com/tik9/pluralsight-skill-test

**Pull request closed without merging**
