### PR TITLE
Update machine-learning-quiz.md

### PR DESCRIPTION
**Pull request by chilcot**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@chilcot could you please fix conflicts, thanks!

**Review by chilcot — COMMENTED** [review]
B

**Comment by Ebazhanov** [comment]
> B

yes or no ??? ))))))

**Comment by chilcot** [comment]
Yes

**Review by Ebazhanov — APPROVED** [review]
@chilcot thank you for your valuable contribution!!!!! :muscle:

**Comment by Ebazhanov** [comment]
@all-contributors please add @chilcot  for design

**Pull request merged**
