### PR TITLE
Update more Java Test Questions

### PR DESCRIPTION
**Pull request by JohnMai1994**
👍 Although I didn't pass the test, but i still mark down some questions. Thank you for your open source 💯

### CODE REVIEW

**Comment by mohsinmsm** [comment]
For the Question #60, shouldn't it be option **B)** "new MagicPower().castSpell("expecto patronum")" cause for option **A** we will be getting compiler error saying 'castSpell(java.lang.String)' in 'MagicPower' cannot be applied to '()'. Notice the String argument in the method definition.

**Comment by JohnMai1994** [comment]
Sorry, this is my first time to contribute code on github. Thank you for review 👍

**Review by Ebazhanov — APPROVED** [review]
Thank you @JohnMai1994! Very clean and good PR, :+1: Approved and I will add you as a contributor!

**Comment by Ebazhanov** [comment]
> For the Question no. 60, shouldn't it be option **B)** "new MagicPower().castSpell("expecto patronum")" cause for option **A** we will be getting compiler error saying 'castSpell(java.lang.String)' in 'MagicPower' cannot be applied to '()'. Notice the String argument in the method definition.

good note @mohsinmsm -> TEAM :rocket:

**Comment by Ebazhanov** [comment]
@all-contributors please add @JohnMai1994 for design, code

**Pull request merged**
