### PR TITLE
Update microsoft-power-bi-quiz.md

### PR DESCRIPTION
**Pull request by Artmasque**
Q11 answered, proof link: https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-query-overview
Q13 answered, proof link: https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting, https://www.edureka.co/community/26060/how-do-i-undo-something-in-power-bi
Q18 answered, proof link: https://docs.microsoft.com/en-us/power-bi/visuals/service-getting-started-with-color-formatting-and-axis-properties

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@Artmasque sorry for the later reply but could you please add prof links directly into *.md file, the reason after I merge you PR your message will disappear but if you put it inside the code it will live forever. Thank you in advance!

**Comment by Artmasque** [comment]
> @Artmasque sorry for the later reply but could you please add prof links directly into *.md file, the reason after I merge you PR your message will disappear but if you put it inside the code it will live forever. Thank you in advance!

Sure, I just wasn't sure it's necessary. Shall add soon:)

**Review by Ebazhanov — APPROVED** [review]
Thank you @Artmasque now it looks complete! :heart_eyes:

**Comment by Ebazhanov** [comment]
@all-contributors please add @Artmasque for design, code

**Pull request merged**
