### PR TITLE
Correction in Java.md

### PR DESCRIPTION
**Pull request by TheShubham-K**

### CODE REVIEW

**Review by Ebazhanov — CHANGES_REQUESTED** [review]
@TheShubham-K, very good improvements but before we merge, you should fix conflicts between your branch and master, please let me know when you will finish it! Have a good holiday!

**Comment by TheShubham-K** [comment]
> @TheShubham-K, very good improvements but before we merge, you should fix conflicts between your branch and master, please let me know when you will finish it! Have a good holiday!

Hey,  @Ebazhanov  i have resolved the conflict , now you can merge it int the main branch

**Review by Ebazhanov — APPROVED** [review]
Thanks, @TheShubham-K for the correction and adding the answer! Super :+1:

**Comment by Ebazhanov** [comment]
@all-contributors please add @TheShubham-K for design, code

**Pull request merged**
