### PR TITLE
upload MATLAB quiz solutions

### PR DESCRIPTION
**Pull request by Hephaest**
Dear @Ebazhanov ,

I have solved the MATLAB quiz problem by myself and passed the LinkedIn MATLAB skill assessment. In these 2 days, I have collected 40+ problems. These solutions could help people who are still seeking a bit of help.

Thanks for reviewing my codes in advance. :heartpulse:

### CODE REVIEW

**Comment by Hephaest** [comment]
Hi @Ebazhanov , sorry for bothering you, but would you please explain the detailed reason for "Resource not accessible by integration." This error warning is very confusing.

**Comment by Ebazhanov** [comment]
> Resource not accessible by integration.

no worries all good! you have created PR that's mean it is work!

**Comment by Hephaest** [comment]
@Ebazhanov 
Thanks for responding to my questions on such short notice. Would you mind helping me review and merge this pull request since nothing else can I do (e.g., assign reviewers, etc.). If there is anything I need to modify, please feel free to contact me. :sparkling_heart:

**Review by Ebazhanov — APPROVED** [review]
Well, what I can say, you did good job -> passed test, and shared your experience with other people, so God bless you @Hephaest :pray:
FYI will add reference link to your new quiz in Readme

**Comment by Ebazhanov** [comment]
@all-contributors please add @Hephaest for code, design

**Pull request merged**
