### PR TITLE
Update JavaScript Quiz

### PR DESCRIPTION
**Pull request by flyingSquirrel-dev**
I am not sure that the quiz no.50 has any problems to run.
Code looks good, and JavaScript Engine is able to understand it I guess.

However, I think The condition in the ternary is using the assignment operator. is close to the correct answer because the others can not be the answer.

Please give me any feedbacks! :)

### CODE REVIEW

**Comment by flyingSquirrel-dev** [comment]
Just wondering the reason why commit bb569cd was not passed?

**Comment by Ebazhanov** [comment]
> Just wondering the reason why commit [bb569cd](https://github.com/Ebazhanov/in-quiz-questions/commit/bb569cdaa008eea28762e8813e89135f5657b05f) was not passed?

yes, I would be happy if you can help with it 
https://github.com/Ebazhanov/in-quiz-questions/pull/305/checks?check_run_id=1001100849
I still was not able to find the solution

**Review by Ebazhanov — APPROVED** [review]
Great job! thanks for contributing!!!

**Comment by Ebazhanov** [comment]
@all-contributors please add @flyingSquirrel-dev for design

**Comment by Ebazhanov** [comment]
> I am not sure that the quiz no.50 has any problems to run.
> Code looks good, and JavaScript Engine is able to understand it I guess.
> 
> However, I think The condition in the ternary is using the assignment operator. is close to the correct answer because the others can not be the answer.
> 
> Please give me any feedbacks! :)

FYI have created post on SO regarding this question, hope we can get some feedback from there 
https://stackoverflow.com/questions/63485372/quiz-question-the-following-program-has-a-problem-what-is-it

**Comment by flyingSquirrel-dev** [comment]
Wow, thanks :) I think the answer I chose is right :)

**Pull request merged**
